version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Nargonath
  assignees:
  - Nargonath
  labels:
  - dependency
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  commit-message:
    prefix: fix
    prefix-development: build
    include: scope
